### PR TITLE
update docs link

### PR DESCRIPTION
**Pull request by swryan**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

@bollwyvl   this is a minor change to the docs link in the README... feel free to incorporate into the next build

### CODE REVIEW

**Comment by swryan** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
More releases are fine!

As you have have seen, your changes got blown away after the re-render: this actually gets sourced from `meta.yaml#/about/doc_url`, so you'll want to update that, and increment the `build_number`, then _re_-rerender.

**Comment by bollwyvl** [comment]
Also, feel free to add yourself as a `#/extra/recipe-maintainers`... _most_ of the time, I try to handle the bot PRs in about a day, but but more eyes are always good.

**Comment by swryan** [comment]
@conda-forge-admin, please rerender

**Comment by swryan** [comment]
> Also, feel free to add yourself as a `#/extra/recipe-maintainers`... _most_ of the time, I try to handle the bot PRs in about a day, but but more eyes are always good.

clearly I'm not qualified ;)

**Comment by bollwyvl** [comment]
> clearly I'm not qualified ;)

80% of the time, it's just pressing _Merge_ when a PR is green, maybe tweaking a few deps and asking for a re-render.

**Comment by bollwyvl** [comment]
Though one real gotcha is that first checklist item: any PR merged to a branch on this repo :shipit: if it passes.

**Comment by bollwyvl** [comment]
Well, and also occasionally adding a test skip, unless it seems _really_ egregious/blocking:

```
test_coloring.py:SimulColoringRevScipyTestCase.test_dynamic_total_coloring
```

If this is a flaky test, sometimes rekicking the CI by closing the feedstock and re-opening will clear it up... but then it's always good to watch when it is _actually_ being published on a `merge` to main. So i'll often just skip and adjust the coverage threshold, if present.

**Comment by bollwyvl** [comment]
Have brought forward this change onto #44, will close this out, thanks again @swryan :heart: 

Note, however; i don't think this will have any impact on `anaconda.org` :crying_cat_face:

**Comment by swryan** [comment]
great thanks!

**Pull request closed without merging**
